[package]
name = "tower-web"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[workspace]

members = [
  "./",
  "tower-web-macros",
]

[dependencies]
futures = "0.1.18"
http = "0.1.5"
hyper = { version = "0.11.22", default-features = false, features = ["compat"] }
tokio = "0.1.3"
tower = { git = "https://github.com/tower-rs/tower" }
tower-web-macros = { version = "0.1.0", path = "tower-web-macros" }
proc-macro-hack = "0.4.0"
