[package]
name = "tower-web"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[workspace]

members = [
  "./",
  "tower-web-macros",
  "tower-web-examples",
]

[dependencies]
bytes = "0.4.7"
futures = "0.1.21"
http = "0.1.5"
hyper = "0.12.1"
log = "0.4.1"
tokio = "0.1.6"
tower-service = { git = "https://github.com/tower-rs/tower" }

# Serializing responses, deserializing requests
serde = "1.0.32"
serde_json = "1.0.11"
serde_plain = "0.3.0"

# Code gen
tower-web-macros = { version = "0.1.0", path = "tower-web-macros" }
proc-macro-hack = "0.4.0"

[dev-dependencies]
serde_derive = "1.0.32"
