[package]
name = "tower-web"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[workspace]

members = [
  "./",
  "tower-web-macros",
]

[dependencies]
bytes = "0.4.6"
futures = "0.1.18"
http = "0.1.5"
hyper = { version = "0.11.22", default-features = false, features = ["compat"] }
log = "0.4.1"
tokio = "0.1.3"
tower = { git = "https://github.com/tower-rs/tower" }

# Serializing responses, deserializing requests
serde = "1.0.32"
serde_json = "1.0.11"

# Code gen
tower-web-macros = { version = "0.1.0", path = "tower-web-macros" }
proc-macro-hack = "0.4.0"

[dev-dependencies]
serde_derive = "1.0.32"
