[package]
name = "tower-web-macros"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.4.0"
proc-macro2 = "0.4.4"
quote = "0.6.3"
syn = { version = "0.14.1", features = ["full", "fold", "extra-traits"] }
